/**
 * Created by Pat on 9/12/2016.
 */
export default {
  ACTIONS : {
    LOAD_COURSES_SUCCESS : 'LOAD_COURSES_SUCCESS',
    SAVE_COURSE_SUCCESS : 'SAVE_COURSE_SUCCESS',
    CREATE_COURSE_SUCCESS : 'CREATE_COURSE_SUCCESS',

    LOAD_COURSES_FAILURE : 'LOAD_COURSES_FAILURE',

    LOAD_AUTHORS_SUCCESS : 'LOAD_AUTHORS_SUCCESS',

    BEGIN_AJAX_CALL : 'BEGIN_AJAX_CALL'
  }
};
